### PR TITLE
Re-render feedstock and fix macOS build

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Obviously we were to optimistic in staged-recipes: even with recent macOS SDK (I tried with 10.13, 10.14 and 10.15) some tests (it seems the one that use ogre) fail with error:
~~~
2021-03-21T17:32:25.5666090Z       Start  7: UNIT_Lidar_TEST
2021-03-21T17:32:26.9870450Z  7/32 Test  #7: UNIT_Lidar_TEST .............................Subprocess aborted***Exception:   1.42 sec
2021-03-21T17:32:26.9873850Z dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
2021-03-21T17:32:26.9875360Z   Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
2021-03-21T17:32:26.9876840Z   Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
2021-03-21T17:32:26.9877880Z 
2021-03-21T17:32:26.9878840Z       Start  8: check_UNIT_Lidar_TEST
2021-03-21T17:32:27.0274680Z  8/32 Test  #8: check_UNIT_Lidar_TEST .......................   Passed    0.04 sec
2021-03-21T17:32:27.0277030Z       Start  9: UNIT_Camera_TEST
2021-03-21T17:32:27.1246830Z  9/32 Test  #9: UNIT_Camera_TEST ............................Subprocess aborted***Exception:   0.10 sec
2021-03-21T17:32:27.1247980Z dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
2021-03-21T17:32:27.1249000Z   Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
2021-03-21T17:32:27.1250280Z   Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
2021-03-21T17:32:27.1250760Z 
2021-03-21T17:32:27.1629160Z       Start 10: check_UNIT_Camera_TEST
2021-03-21T17:32:27.2042900Z 10/32 Test #10: check_UNIT_Camera_TEST ......................   Passed    0.04 sec
2021-03-21T17:32:27.2044880Z       Start 11: UNIT_ImuSensor_TEST
2021-03-21T17:32:27.4684080Z 11/32 Test #11: UNIT_ImuSensor_TEST .........................   Passed    0.26 sec
2021-03-21T17:32:27.4685870Z       Start 12: check_UNIT_ImuSensor_TEST
2021-03-21T17:32:27.5079550Z 12/32 Test #12: check_UNIT_ImuSensor_TEST ...................   Passed    0.04 sec
2021-03-21T17:32:27.5082660Z       Start 13: INTEGRATION_camera_plugin
2021-03-21T17:32:27.5701250Z 13/32 Test #13: INTEGRATION_camera_plugin ...................Subprocess aborted***Exception:   0.06 sec
2021-03-21T17:32:27.5702390Z dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
2021-03-21T17:32:27.5703270Z   Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
2021-03-21T17:32:27.5704100Z   Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
2021-03-21T17:32:27.5704570Z 
2021-03-21T17:32:27.6114660Z       Start 14: check_INTEGRATION_camera_plugin
2021-03-21T17:32:27.6507430Z 14/32 Test #14: check_INTEGRATION_camera_plugin .............   Passed    0.04 sec
2021-03-21T17:32:27.6509190Z       Start 15: INTEGRATION_depth_camera_plugin
2021-03-21T17:32:27.7507110Z 15/32 Test #15: INTEGRATION_depth_camera_plugin .............Subprocess aborted***Exception:   0.10 sec
2021-03-21T17:32:27.7508290Z dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
2021-03-21T17:32:27.7509150Z   Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
2021-03-21T17:32:27.7509980Z   Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
2021-03-21T17:32:27.7510430Z 
2021-03-21T17:32:27.7920270Z       Start 16: check_INTEGRATION_depth_camera_plugin
2021-03-21T17:32:27.8317550Z 16/32 Test #16: check_INTEGRATION_depth_camera_plugin .......   Passed    0.04 sec
2021-03-21T17:32:27.8319460Z       Start 17: INTEGRATION_gpu_lidar_sensor_plugin
2021-03-21T17:32:27.9348280Z 17/32 Test #17: INTEGRATION_gpu_lidar_sensor_plugin .........Subprocess aborted***Exception:   0.10 sec
2021-03-21T17:32:27.9349400Z dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
2021-03-21T17:32:27.9350290Z   Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
2021-03-21T17:32:27.9351110Z   Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
2021-03-21T17:32:27.9351570Z 
2021-03-21T17:32:27.9750710Z       Start 18: check_INTEGRATION_gpu_lidar_sensor_plugin
2021-03-21T17:32:28.0163460Z 18/32 Test #18: check_INTEGRATION_gpu_lidar_sensor_plugin ...   Passed    0.04 sec
2021-03-21T17:32:28.0169130Z       Start 19: INTEGRATION_rgbd_camera_plugin
2021-03-21T17:32:28.1193440Z 19/32 Test #19: INTEGRATION_rgbd_camera_plugin ..............Subprocess aborted***Exception:   0.10 sec
2021-03-21T17:32:28.1194580Z dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
2021-03-21T17:32:28.1195530Z   Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
2021-03-21T17:32:28.1196400Z   Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
2021-03-21T17:32:28.1197370Z 
2021-03-21T17:32:28.1606420Z       Start 20: check_INTEGRATION_rgbd_camera_plugin
2021-03-21T17:32:28.1997670Z 20/32 Test #20: check_INTEGRATION_rgbd_camera_plugin ........   Passed    0.04 sec
2021-03-21T17:32:28.1999290Z       Start 21: INTEGRATION_thermal_camera_plugin
2021-03-21T17:32:28.3172150Z 21/32 Test #21: INTEGRATION_thermal_camera_plugin ...........Subprocess aborted***Exception:   0.12 sec
2021-03-21T17:32:28.3173300Z dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
2021-03-21T17:32:28.3174230Z   Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
2021-03-21T17:32:28.3175420Z   Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
2021-03-21T17:32:28.3175880Z 
~~~

**Comment by traversaro** [comment]
@Tobias-Fischer @wolfv do you have any idea regarding the macOS error:
~~~
2021-03-21T17:32:27.7508290Z dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
2021-03-21T17:32:27.7509150Z   Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
2021-03-21T17:32:27.7509980Z   Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
~~~

**Comment by wolfv** [comment]
hmm, that's weird. looks like we need to link to BLAS, and it currently decides to take the system BLAS (Accelerate framework). I don't know this part of OS X very well ... we could ask the conda-forge Gitter community, they might have run across this before.
It might be helpful to run the build with verbose flags to see what exactly is linked.

I can see that the conda-forge build system pulls in OpenBLAS, but apparently it's linking against Accelerate Blas? It might also be a mixup with headers vs. linked library?

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
