### PR TITLE
Aarch build

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready for review @conda-forge/libignition-sensors

**Comment by traversaro** [comment]
I wonder if there is some problem in the tests due to the fact that on Azure the build is cross-compiled and then the tests are emulated. Let's try to switch to Travis (fully aarch64 build) to see if this problem is solved.

**Comment by traversaro** [comment]
> > I wonder if there is some problem in the tests due to the fact that on Azure the build is cross-compiled and then the tests are emulated. Let's try to switch to Travis (fully aarch64 build) to see if this problem is solved.
> 
> Sorry, this is only true for tests that run in the tests sections. This are "tests" but are actually steps of the build section that should be skipped in cross-compilation, not sure what is happening. By the way, I have a similar failure in [conda-forge/idyntree-feedstock#37](https://github.com/conda-forge/idyntree-feedstock/pull/37), and I remember that back in time that was working fine.

Actually, I remember wrongly, apparently the scripts are passing [`CMAKE_CROSSCOMPILING_EMULATOR`](https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING_EMULATOR.html) to run also CMake tests. However, this apparently it is not working for ign-sensors, let's try to switch to Travis as I originally proposed.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> > I wonder if there is some problem in the tests due to the fact that on Azure the build is cross-compiled and then the tests are emulated. Let's try to switch to Travis (fully aarch64 build) to see if this problem is solved.
> 
> Sorry, this is only true for tests that run in the tests sections. This are "tests" but are actually steps of the build section that should be skipped in cross-compilation, not sure what is happening. By the way, I have a similar failure in [conda-forge/idyntree-feedstock#37](https://github.com/conda-forge/idyntree-feedstock/pull/37), and I remember that back in time that was working fine.

The problem in the idyntree PR is different, it is that required Python libraries are not found by CMake.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Switching to Travis worked fine.

**Comment by wolfv** [comment]
Awesome! Thanks for the effort! Soon we can have desktop-full on linux-aarch64 :)

**Pull request merged**
