### PR TITLE
Bump version to 6.0.0

### PR DESCRIPTION
**Pull request by traversaro**
This was done manually due to https://github.com/conda-forge/libignition-gazebo-feedstock/issues/24 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
All test pass successfully if I set the following env variables:
~~~
export OGRE_RESOURCE_PATH=$CONDA_PREFIX/lib/OGRE/
export IGN_RENDERING_RESOURCE_PATH=$CONDA_PREFIX/share/ignition/ignition-rendering6
~~~

So probably there is an issue similar to https://github.com/conda-forge/libignition-rendering4-feedstock/issues/25#issuecomment-939092507, just on macOS .

**Comment by traversaro** [comment]
> All test pass successfully if I set the following env variables:
> 
> ```
> export OGRE_RESOURCE_PATH=$CONDA_PREFIX/lib/OGRE/
> export IGN_RENDERING_RESOURCE_PATH=$CONDA_PREFIX/share/ignition/ignition-rendering6
> ```
> 
> So probably there is an issue similar to [conda-forge/libignition-rendering4-feedstock#25 (comment)](https://github.com/conda-forge/libignition-rendering4-feedstock/issues/25#issuecomment-939092507), just on macOS .

Note that even after setting those env variables, the test pass but an error is printed: 
~~~
test 15
    Start 15: INTEGRATION_camera

15: Test command: /Users/traversaro/src/ign-sensors/build/bin/INTEGRATION_camera "--gtest_output=xml:/Users/traversaro/src/ign-sensors/build/test_results/INTEGRATION_camera.xml"
15: Test timeout computed to be: 240
15: [==========] Running 1 test from 1 test case.
15: [----------] Global test environment set-up.
15: [----------] 1 test from CameraSensor/CameraSensorTest
15: [ RUN      ] CameraSensor/CameraSensorTest.ImagesWithBuiltinSDF/ogre
15: [Err] [OgreRenderEngine.cc:462] Unable to load Ogre Plugin[/Users/traversaro/mambaforge/envs/ignsensors/lib/OGRE]. Rendering will not be possible.Make sure you have installed OGRE properly.
15: [Msg] Loading plugin [ignition-rendering-ogre]
15: [Dbg] [CameraSensor.cc:271] Camera images for [camera1] advertised on [/test/integration/CameraPlugin_imagesWithBuiltinSDF]
15: [Dbg] [CameraSensor.cc:524] Camera info for [camera1] advertised on [/test/integration/camera_info]
15: [Dbg] [CameraSensor.cc:357] Enabling camera sensor: 'camera1' data generation.
15: [       OK ] CameraSensor/CameraSensorTest.ImagesWithBuiltinSDF/ogre (242 ms)
15: [----------] 1 test from CameraSensor/CameraSensorTest (242 ms total)
15: 
15: [----------] Global test environment tear-down
15: [==========] 1 test from 1 test case ran. (242 ms total)
15: [  PASSED  ] 1 test.
1/2 Test #15: INTEGRATION_camera ...............   Passed    0.27 sec
~~~

However, I have the impression that that error is just a spurious error. Indeed, I tried to run the `examples/save_image` example, and even there the error is printed, but then the image is saved, proving that the rendering happened even if the error is printed:
~~~
(ignsensors) Silvios-iMac:build traversaro$ ./save_image 
[Err] [OgreRenderEngine.cc:462] Unable to load Ogre Plugin[/Users/traversaro/mambaforge/envs/ignsensors/lib/OGRE]. Rendering will not be possible.Make sure you have installed OGRE properly.
Saving image.png
~~~

image

**Comment by traversaro** [comment]
Hopefully https://github.com/conda-forge/libignition-rendering4-feedstock/pull/27 should solve all the problem with the tests, and once that is merge we can merge this PR as well.

**Comment by traversaro** [comment]
Just tested with `libignition-rendering6:  6.0.1-hdd72079_1` (i.e. the build after https://github.com/conda-forge/libignition-rendering4-feedstock/pull/27). As in the case of ign-rendering, now tests that involve rendering are failing for both macOS and Windows, but that is due to the Azure headless environment as I tested manually on normal systems and the tests are passing fine.

**Comment by Tobias-Fischer** [comment]
Great, shall we merge this in?

**Pull request merged**
